# Site
title: 王子亭的博客
subtitle:
description:
author: 王子亭
email: jysperm@gmail.com
language: zh-CN

# URL
url: https://jysperm.me
root: /
permalink: :year/:month/:title/
tag_dir: tag
archive_dir: ''
category_dir: ''
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :year-:month-:day#:title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: 随笔
category_map:
  技术: technology
  生活: live
  随笔: note
tag_map:
  软件工程: 软件工程
  PHP: php

# Archives
archive: 2
category: 2
tag: 2

# Server
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# Date / Time format
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
per_page: 3
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
theme: jysperm
exclude_generator:

# Deployment
deploy:
  type: rsync
  host: jysperm.me
  user: jysperm
  root: /home/jysperm/blog-public

feed:
  type: atom
  path: atom.xml
  limit: 30
