## Services
google_analytics: 'UA-49193300-1'
duoshuo: 'jyprince'

## Meta
rss: https://jysperm.me/atom.xml
favicon: /avatars/v5.png
icon: /avatars/v5.png
source_url: 'https://github.com/jysperm/blog/blob/master/source/'
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  '关于精子': /about
  '简历': /profile
  '链接': /links
  '书单': /booklist
  '碎语': /tweets
  '所有日志': /list
  '广告': /ad

right_menus:
  'RSS': /atom.xml
  'fork on Github':
    target: '_blank'
    href: 'https://github.com/jysperm/blog'

## Banners && Widgets
banners:
  jade: |
    a(target='_blank', href='https://github.com/jysperm/hexo-theme-simpleblock') 与精子同款的博客主题 simpleblock 现已发布！

widgets:
  -
    markdown: |
      精子生于 1995.11.25, 20 岁，英文 ID jysperm.

      * 有一个 [精子粉丝团](https://jybox.net)
      * [皮蛋](http://pidan.cat) 和 [豆腐](http://doufu.cat) 的主人
      * 创建了 [Atom 中文社区](https://atom-china.org)
      * 坚持十余年的 [独立博客](https://jysperm.me) 作者
      * 高中退学，就职于 [LeanCloud](https://leancloud.cn)
      * 在 [Github](https://github.com/jysperm) 上积极参与开源社区

  -
    tags: true

  -
    jade: |
      h2 关注精子的微信公众号
      img(alt='weixin-qrcode', style='width: 100%', src='http://7xkmw1.com1.z0.glb.clouddn.com/weixin-qrcode.png')
      p 公众号会推送精子的博客日志、精子的产品和项目的最新动态，以及皮蛋和豆腐的照片。
  -
    archives: true

  -
    copyright: true

## SNS
sns:
  qq: '184300584'
  qun: '61137226'
  v2ex: 'jybox'
  mobile: '17091927884'
  github: 'jysperm'
  keybase: 'jysperm'
  zhihu: 'jysperm'
  google_plus: '+王子亭jysperm'
  segmentfault: 'jysperm'
  twitter: 'jysperm'
  bitcoin: '13v2BTCMZMHg5v87susgg86HFZqXERuwUd'
